version: '3'
services:

  db:
    build: ms-user-profile/src/main/docker/postgres
    image: micro/postgres
    container_name: db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - 5432:5432

  swaggerui:
    image: swaggerapi/swagger-ui
    container_name: swaggerui
    environment:
     - API_URL=http://localhost:8080/api-docs/swagger.json
    ports:
      - 8081:8080

  ms-user-profile:
    build: ms-user-profile
    image: micro/ms-user-profile
    container_name: ms-user-profile
    restart: unless-stopped
    depends_on:
      - db
    command: sh -c './wait-for db:5432 -- java -jar /app/service.jar'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=demo
      - DB_USER=demo
      - DB_PASS=demo
    ports:
      - 8080:8080
